title: Spotify Open Source Projects
description: Open Source Software developed at Spotify
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spotify.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SpotifyEng
github_username: Spotify
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
  - assets/html
  - package.json
  - yarn.lock
  - README.md
